// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN2j1XwVhoeiaVZjGmJAUZWERdkcYhsiY',
    appId: '1:40045091848:web:158e6e434a9becd86205bd',
    messagingSenderId: '40045091848',
    projectId: 'shopping-app-d7aa1',
    authDomain: 'shopping-app-d7aa1.firebaseapp.com',
    storageBucket: 'shopping-app-d7aa1.appspot.com',
    measurementId: 'G-JTE18RKF6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD59LNYFSi7KnTxWU9mZcGVQAFUopsBHzs',
    appId: '1:40045091848:android:4b06f578f44d98216205bd',
    messagingSenderId: '40045091848',
    projectId: 'shopping-app-d7aa1',
    storageBucket: 'shopping-app-d7aa1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQXW8zP8XNz7vTaoNx0HDdABlMYoaHfQQ',
    appId: '1:40045091848:ios:6ddd48a713033a726205bd',
    messagingSenderId: '40045091848',
    projectId: 'shopping-app-d7aa1',
    storageBucket: 'shopping-app-d7aa1.appspot.com',
    androidClientId: '40045091848-olonfo3admv6no3j16g9mvauh6thottq.apps.googleusercontent.com',
    iosClientId: '40045091848-ljeemo1ahjjn9t6pv1dkb2odp1t16rl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQXW8zP8XNz7vTaoNx0HDdABlMYoaHfQQ',
    appId: '1:40045091848:ios:6ddd48a713033a726205bd',
    messagingSenderId: '40045091848',
    projectId: 'shopping-app-d7aa1',
    storageBucket: 'shopping-app-d7aa1.appspot.com',
    androidClientId: '40045091848-olonfo3admv6no3j16g9mvauh6thottq.apps.googleusercontent.com',
    iosClientId: '40045091848-ljeemo1ahjjn9t6pv1dkb2odp1t16rl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp',
  );
}
